version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.4.0
  deploys: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-scripts:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install bats
          command: |
            sudo apt-get update -qq && sudo apt-get install -y -qq bats
      - run:
          name: Run script unit tests
          command: bats tests/scripts.bats

workflows:
  test-deploy:
    jobs:
      - test-scripts:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          name: publish_prod
          orb_name: circleci/deploys
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: orb-publisher
          filters: *release-filters
